@ECHO OFF

SET KEYTOOL="%JAVA_HOME%"\bin\keytool
SET SECRET_DIR=..\secret
IF NOT EXIST "%SECRET_DIR%" (
  MKDIR %SECRET_DIR%
)

SET CA_DNAME=___DO_NOT_TRUST___Valori_workshop_CA
SET CA_ALIAS=rootCA
SET CA_CRT_FILE=%SECRET_DIR%\%CA_ALIAS%.crt
SET CA_KEYSTORE=%SECRET_DIR%\CA-keystore.p12
SET TRUSTSTORE=%SECRET_DIR%\truststore.jks
SET KEYSTORE=%SECRET_DIR%\keystore.p12

SET DNAME=%~1
SET CRS_FILE=%SECRET_DIR%\%DNAME%.csr
SET CRT_FILE=%SECRET_DIR%\%DNAME%.crt
