@ECHO OFF

SET CA_PASSWORD=ValoriWorkshopCAPassword
SET TRUSTSTORE_PASSWORD=TrustStorePassword
SET KEYSTORE_PASSWORD=KeyStorePassword

SET MY_DNAME=valori.example.com

CALL generateRootCA
CALL createTrustStore
CALL generateKeyPair %MY_DNAME%
CALL createCSR %MY_DNAME%
CALL signCSRs %SECRET_DIR%
CALL importRootCA
CALL importCertificate %MY_DNAME%

SET CA_PASSWORD=
SET TRUSTSTORE_PASSWORD=
SET KEYSTORE_PASSWORD=
